version: "3.8"

services:
  cloud_app:
    image: cloud_node_app:latest
    container_name: cloud_main_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq_cloud
      - mqtt_cloud
    environment:
      - RABBITMQ_HOST=rabbitmq_cloud
      - CLOUD_RABBITMQ_HOST=rabbitmq_cloud
      - CLOUD_MQTT_HOST=mqtt_cloud
      - CLOUD_MQTT_PORT=1883
      - APP_HOST_PORT=8081
    ports:
      - "8082:8081"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - aqtf_shared_network
    command: python3 -m cloud.communication.cloud_messaging
    volumes:
      - ./models:/app/models
      - ./status:/app/status
      - /sys/class/net:/host_sys/class/net:ro

  rabbitmq_cloud:
    image: rabbitmq:3-management
    container_name: rabbitmq_cloud
    ports:
      - "5673:5672"    # Messaging port (εξωτερική 5673)
      - "15673:15672"  # Management UI (εξωτερική 15673)
    networks:
      - aqtf_shared_network

  mqtt_cloud:
    image: eclipse-mosquitto
    container_name: mqtt_cloud
    ports:
      - "1884:1883"    # MQTT port (εξωτερική 1884 για να μην κολλάει με του Fog)
    networks:
      - aqtf_shared_network
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

networks:
  aqtf_shared_network:
    external: true