"""
Synthetic Energy Consumption Data Generator
============================================
Generates 90 days of energy consumption data for 50 houses with non-IID characteristics.

Output: data/house_{1..50}/input_data.csv
Format: timestamp, consumption_kwh
(All other features are generated by data_preprocessing.py)
"""

import os
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

# ── Reproducibility ─────────────────────────────────────────────
np.random.seed(42)

# ── Configuration ───────────────────────────────────────────────
N_HOUSES   = 50
DAYS       = 90
FREQ_MIN   = 10          # 10-minute intervals → 144 points/day
START_DATE = datetime(2024, 1, 1)

# ── House profiles (non-IID) ────────────────────────────────────
HOUSE_PROFILES = {
    # --- Original 10 houses (unchanged) ---
    1: {
        "name": "Small apartment, morning peak",
        "base_kwh":     0.3,
        "peak_hour":    7,
        "peak_kwh":     1.8,
        "evening_hour": 19,
        "evening_kwh":  1.2,
        "season_bias":  "winter",
        "noise_std":    0.08,
        "weekend_factor": 1.3,
    },
    2: {
        "name": "Large house, evening peak",
        "base_kwh":     0.7,
        "peak_hour":    20,
        "peak_kwh":     3.5,
        "evening_hour": 21,
        "evening_kwh":  3.0,
        "season_bias":  "summer",
        "noise_std":    0.15,
        "weekend_factor": 1.5,
    },
    3: {
        "name": "Medium house, work-from-home",
        "base_kwh":     0.5,
        "peak_hour":    12,
        "peak_kwh":     2.2,
        "evening_hour": 18,
        "evening_kwh":  1.8,
        "season_bias":  "neutral",
        "noise_std":    0.10,
        "weekend_factor": 1.1,
    },
    4: {
        "name": "Elderly couple, all-day moderate",
        "base_kwh":     0.6,
        "peak_hour":    11,
        "peak_kwh":     1.5,
        "evening_hour": 16,
        "evening_kwh":  1.4,
        "season_bias":  "winter",
        "noise_std":    0.07,
        "weekend_factor": 1.0,
    },
    5: {
        "name": "Young professionals, late night",
        "base_kwh":     0.25,
        "peak_hour":    22,
        "peak_kwh":     2.0,
        "evening_hour": 23,
        "evening_kwh":  1.8,
        "season_bias":  "summer",
        "noise_std":    0.12,
        "weekend_factor": 1.8,
    },
    6: {
        "name": "Student flat, irregular schedule",
        "base_kwh":     0.2,
        "peak_hour":    14,
        "peak_kwh":     1.5,
        "evening_hour": 1,
        "evening_kwh":  1.3,
        "season_bias":  "neutral",
        "noise_std":    0.18,
        "weekend_factor": 2.0,
    },
    7: {
        "name": "Family with children, double morning peak",
        "base_kwh":     0.8,
        "peak_hour":    8,
        "peak_kwh":     4.0,
        "evening_hour": 18,
        "evening_kwh":  3.5,
        "season_bias":  "winter",
        "noise_std":    0.20,
        "weekend_factor": 1.6,
    },
    8: {
        "name": "Home office with EV charging",
        "base_kwh":     0.9,
        "peak_hour":    10,
        "peak_kwh":     5.0,
        "evening_hour": 20,
        "evening_kwh":  4.5,
        "season_bias":  "summer",
        "noise_std":    0.25,
        "weekend_factor": 1.2,
    },
    9: {
        "name": "Retired single, very low consumption",
        "base_kwh":     0.15,
        "peak_hour":    9,
        "peak_kwh":     0.8,
        "evening_hour": 15,
        "evening_kwh":  0.7,
        "season_bias":  "winter",
        "noise_std":    0.05,
        "weekend_factor": 1.05,
    },
    10: {
        "name": "Shift worker, inverted profile",
        "base_kwh":     0.3,
        "peak_hour":    6,
        "peak_kwh":     2.5,
        "evening_hour": 8,
        "evening_kwh":  2.0,
        "season_bias":  "neutral",
        "noise_std":    0.13,
        "weekend_factor": 0.8,
    },

    # --- Houses 11–50: νέα non-IID προφίλ ---
    11: {
        "name": "Young couple, cooking evening peak",
        "base_kwh":     0.35,
        "peak_hour":    19,
        "peak_kwh":     2.3,
        "evening_hour": 21,
        "evening_kwh":  1.6,
        "season_bias":  "neutral",
        "noise_std":    0.09,
        "weekend_factor": 1.4,
    },
    12: {
        "name": "Large family, high all-day load",
        "base_kwh":     1.0,
        "peak_hour":    8,
        "peak_kwh":     4.5,
        "evening_hour": 19,
        "evening_kwh":  4.0,
        "season_bias":  "winter",
        "noise_std":    0.22,
        "weekend_factor": 1.7,
    },
    13: {
        "name": "Eco-conscious single, minimal use",
        "base_kwh":     0.08,
        "peak_hour":    7,
        "peak_kwh":     0.6,
        "evening_hour": 20,
        "evening_kwh":  0.5,
        "season_bias":  "neutral",
        "noise_std":    0.03,
        "weekend_factor": 1.1,
    },
    14: {
        "name": "Airbnb host, variable occupancy",
        "base_kwh":     0.4,
        "peak_hour":    10,
        "peak_kwh":     2.8,
        "evening_hour": 22,
        "evening_kwh":  2.5,
        "season_bias":  "summer",
        "noise_std":    0.30,
        "weekend_factor": 2.2,
    },
    15: {
        "name": "Night shift nurse, daytime activity",
        "base_kwh":     0.28,
        "peak_hour":    9,
        "peak_kwh":     1.9,
        "evening_hour": 11,
        "evening_kwh":  1.5,
        "season_bias":  "neutral",
        "noise_std":    0.10,
        "weekend_factor": 0.9,
    },
    16: {
        "name": "Pensioner couple, TV-heavy evenings",
        "base_kwh":     0.55,
        "peak_hour":    10,
        "peak_kwh":     1.3,
        "evening_hour": 20,
        "evening_kwh":  1.8,
        "season_bias":  "winter",
        "noise_std":    0.06,
        "weekend_factor": 1.05,
    },
    17: {
        "name": "Teenager household, gaming nights",
        "base_kwh":     0.4,
        "peak_hour":    16,
        "peak_kwh":     2.6,
        "evening_hour": 23,
        "evening_kwh":  2.4,
        "season_bias":  "neutral",
        "noise_std":    0.16,
        "weekend_factor": 1.9,
    },
    18: {
        "name": "Solar prosumer, midday self-consumption",
        "base_kwh":     0.45,
        "peak_hour":    13,
        "peak_kwh":     1.0,
        "evening_hour": 19,
        "evening_kwh":  2.2,
        "season_bias":  "summer",
        "noise_std":    0.12,
        "weekend_factor": 1.2,
    },
    19: {
        "name": "Remote worker, flat daytime profile",
        "base_kwh":     0.6,
        "peak_hour":    9,
        "peak_kwh":     1.8,
        "evening_hour": 18,
        "evening_kwh":  1.5,
        "season_bias":  "neutral",
        "noise_std":    0.08,
        "weekend_factor": 0.85,
    },
    20: {
        "name": "Small bakery at home, early morning",
        "base_kwh":     0.7,
        "peak_hour":    4,
        "peak_kwh":     3.8,
        "evening_hour": 6,
        "evening_kwh":  2.5,
        "season_bias":  "neutral",
        "noise_std":    0.14,
        "weekend_factor": 1.3,
    },
    21: {
        "name": "Single parent, school schedule",
        "base_kwh":     0.32,
        "peak_hour":    7,
        "peak_kwh":     1.7,
        "evening_hour": 17,
        "evening_kwh":  2.0,
        "season_bias":  "winter",
        "noise_std":    0.09,
        "weekend_factor": 1.5,
    },
    22: {
        "name": "Tech enthusiast, always-on devices",
        "base_kwh":     0.85,
        "peak_hour":    20,
        "peak_kwh":     2.5,
        "evening_hour": 22,
        "evening_kwh":  2.2,
        "season_bias":  "neutral",
        "noise_std":    0.11,
        "weekend_factor": 1.3,
    },
    23: {
        "name": "Minimalist studio, very low base",
        "base_kwh":     0.1,
        "peak_hour":    8,
        "peak_kwh":     0.7,
        "evening_hour": 21,
        "evening_kwh":  0.6,
        "season_bias":  "neutral",
        "noise_std":    0.04,
        "weekend_factor": 1.2,
    },
    24: {
        "name": "Gym at home, morning workout peaks",
        "base_kwh":     0.4,
        "peak_hour":    6,
        "peak_kwh":     2.0,
        "evening_hour": 18,
        "evening_kwh":  1.4,
        "season_bias":  "neutral",
        "noise_std":    0.13,
        "weekend_factor": 1.6,
    },
    25: {
        "name": "Large villa, pool & AC heavy",
        "base_kwh":     1.2,
        "peak_hour":    14,
        "peak_kwh":     6.0,
        "evening_hour": 20,
        "evening_kwh":  4.5,
        "season_bias":  "summer",
        "noise_std":    0.28,
        "weekend_factor": 1.8,
    },
    26: {
        "name": "Couple with baby, constant moderate load",
        "base_kwh":     0.55,
        "peak_hour":    7,
        "peak_kwh":     1.9,
        "evening_hour": 20,
        "evening_kwh":  1.6,
        "season_bias":  "winter",
        "noise_std":    0.08,
        "weekend_factor": 1.1,
    },
    27: {
        "name": "Part-time worker, midday peak",
        "base_kwh":     0.3,
        "peak_hour":    13,
        "peak_kwh":     1.6,
        "evening_hour": 19,
        "evening_kwh":  1.3,
        "season_bias":  "neutral",
        "noise_std":    0.10,
        "weekend_factor": 1.35,
    },
    28: {
        "name": "Electrician, workshop at home",
        "base_kwh":     0.8,
        "peak_hour":    10,
        "peak_kwh":     4.2,
        "evening_hour": 15,
        "evening_kwh":  2.8,
        "season_bias":  "neutral",
        "noise_std":    0.20,
        "weekend_factor": 0.7,
    },
    29: {
        "name": "Music producer, studio overnight",
        "base_kwh":     0.45,
        "peak_hour":    23,
        "peak_kwh":     2.1,
        "evening_hour": 2,
        "evening_kwh":  1.8,
        "season_bias":  "neutral",
        "noise_std":    0.14,
        "weekend_factor": 1.6,
    },
    30: {
        "name": "Seasonal house, winter-heavy",
        "base_kwh":     0.2,
        "peak_hour":    18,
        "peak_kwh":     3.0,
        "evening_hour": 20,
        "evening_kwh":  2.8,
        "season_bias":  "winter",
        "noise_std":    0.17,
        "weekend_factor": 2.0,
    },
    31: {
        "name": "Freelancer, irregular hours",
        "base_kwh":     0.38,
        "peak_hour":    11,
        "peak_kwh":     1.7,
        "evening_hour": 22,
        "evening_kwh":  1.5,
        "season_bias":  "neutral",
        "noise_std":    0.19,
        "weekend_factor": 1.25,
    },
    32: {
        "name": "Diabetic senior, medical devices",
        "base_kwh":     0.5,
        "peak_hour":    8,
        "peak_kwh":     1.1,
        "evening_hour": 14,
        "evening_kwh":  1.0,
        "season_bias":  "winter",
        "noise_std":    0.05,
        "weekend_factor": 1.0,
    },
    33: {
        "name": "University dorm cluster",
        "base_kwh":     0.6,
        "peak_hour":    12,
        "peak_kwh":     2.4,
        "evening_hour": 23,
        "evening_kwh":  2.8,
        "season_bias":  "neutral",
        "noise_std":    0.22,
        "weekend_factor": 2.1,
    },
    34: {
        "name": "Pet grooming home business",
        "base_kwh":     0.5,
        "peak_hour":    9,
        "peak_kwh":     2.6,
        "evening_hour": 16,
        "evening_kwh":  1.5,
        "season_bias":  "neutral",
        "noise_std":    0.12,
        "weekend_factor": 1.7,
    },
    35: {
        "name": "Mountain cabin, heating-dominated",
        "base_kwh":     0.25,
        "peak_hour":    7,
        "peak_kwh":     4.5,
        "evening_hour": 20,
        "evening_kwh":  4.0,
        "season_bias":  "winter",
        "noise_std":    0.20,
        "weekend_factor": 2.5,
    },
    36: {
        "name": "New parents, variable schedule",
        "base_kwh":     0.48,
        "peak_hour":    3,
        "peak_kwh":     1.2,
        "evening_hour": 8,
        "evening_kwh":  1.8,
        "season_bias":  "neutral",
        "noise_std":    0.15,
        "weekend_factor": 1.1,
    },
    37: {
        "name": "Vegetarian household, heavy cooking",
        "base_kwh":     0.4,
        "peak_hour":    12,
        "peak_kwh":     2.0,
        "evening_hour": 19,
        "evening_kwh":  2.3,
        "season_bias":  "neutral",
        "noise_std":    0.11,
        "weekend_factor": 1.4,
    },
    38: {
        "name": "Electric vehicle owner, night charging",
        "base_kwh":     0.5,
        "peak_hour":    1,
        "peak_kwh":     4.0,
        "evening_hour": 3,
        "evening_kwh":  3.5,
        "season_bias":  "neutral",
        "noise_std":    0.18,
        "weekend_factor": 1.3,
    },
    39: {
        "name": "Artist studio, daytime natural light",
        "base_kwh":     0.22,
        "peak_hour":    15,
        "peak_kwh":     1.1,
        "evening_hour": 19,
        "evening_kwh":  0.9,
        "season_bias":  "neutral",
        "noise_std":    0.08,
        "weekend_factor": 1.5,
    },
    40: {
        "name": "Busy restaurant family, high evening",
        "base_kwh":     0.9,
        "peak_hour":    12,
        "peak_kwh":     5.5,
        "evening_hour": 20,
        "evening_kwh":  5.0,
        "season_bias":  "summer",
        "noise_std":    0.25,
        "weekend_factor": 2.0,
    },
    41: {
        "name": "Couple with elderly parent, daytime care",
        "base_kwh":     0.65,
        "peak_hour":    10,
        "peak_kwh":     1.8,
        "evening_hour": 17,
        "evening_kwh":  1.6,
        "season_bias":  "winter",
        "noise_std":    0.07,
        "weekend_factor": 1.15,
    },
    42: {
        "name": "Weekend-only vacation home",
        "base_kwh":     0.05,
        "peak_hour":    11,
        "peak_kwh":     2.5,
        "evening_hour": 20,
        "evening_kwh":  2.2,
        "season_bias":  "summer",
        "noise_std":    0.10,
        "weekend_factor": 8.0,  # Χρησιμοποιείται κυρίως Σ/Κ
    },
    43: {
        "name": "Tailor workshop at home, morning heavy",
        "base_kwh":     0.45,
        "peak_hour":    9,
        "peak_kwh":     2.8,
        "evening_hour": 14,
        "evening_kwh":  2.0,
        "season_bias":  "neutral",
        "noise_std":    0.11,
        "weekend_factor": 0.6,
    },
    44: {
        "name": "Household with aquarium & terrarium",
        "base_kwh":     0.7,
        "peak_hour":    8,
        "peak_kwh":     1.4,
        "evening_hour": 20,
        "evening_kwh":  1.2,
        "season_bias":  "neutral",
        "noise_std":    0.06,
        "weekend_factor": 1.05,
    },
    45: {
        "name": "Crypto miner, 24h high base load",
        "base_kwh":     2.0,
        "peak_hour":    12,
        "peak_kwh":     2.5,
        "evening_hour": 0,
        "evening_kwh":  2.3,
        "season_bias":  "neutral",
        "noise_std":    0.15,
        "weekend_factor": 1.0,
    },
    46: {
        "name": "Kindergarten teacher, strict schedule",
        "base_kwh":     0.3,
        "peak_hour":    7,
        "peak_kwh":     1.5,
        "evening_hour": 16,
        "evening_kwh":  1.8,
        "season_bias":  "winter",
        "noise_std":    0.07,
        "weekend_factor": 1.6,
    },
    47: {
        "name": "DIY enthusiast, weekend power tools",
        "base_kwh":     0.35,
        "peak_hour":    10,
        "peak_kwh":     1.2,
        "evening_hour": 19,
        "evening_kwh":  1.0,
        "season_bias":  "neutral",
        "noise_std":    0.10,
        "weekend_factor": 2.8,
    },
    48: {
        "name": "Triathlete, early morning training",
        "base_kwh":     0.28,
        "peak_hour":    5,
        "peak_kwh":     1.6,
        "evening_hour": 20,
        "evening_kwh":  1.3,
        "season_bias":  "neutral",
        "noise_std":    0.09,
        "weekend_factor": 1.4,
    },
    49: {
        "name": "Multi-generational household",
        "base_kwh":     1.1,
        "peak_hour":    8,
        "peak_kwh":     5.0,
        "evening_hour": 19,
        "evening_kwh":  4.5,
        "season_bias":  "winter",
        "noise_std":    0.24,
        "weekend_factor": 1.6,
    },
    50: {
        "name": "Minimalist couple, energy monitors",
        "base_kwh":     0.12,
        "peak_hour":    7,
        "peak_kwh":     0.9,
        "evening_hour": 20,
        "evening_kwh":  0.8,
        "season_bias":  "neutral",
        "noise_std":    0.04,
        "weekend_factor": 1.2,
    },
}

def seasonal_factor(date, bias):
    day_of_year = date.timetuple().tm_yday
    angle = 2 * np.pi * day_of_year / 365
    if bias == "winter":
        return 1.0 + 0.35 * np.cos(angle)
    elif bias == "summer":
        return 1.0 + 0.35 * (-np.cos(angle))
    else:
        return 1.0 + 0.10 * np.sin(angle)

def gaussian_peak(hour_float, center, width=1.5, height=1.0):
    return height * np.exp(-0.5 * ((hour_float - center) / width) ** 2)

def generate_house_data(house_id, profile):
    records = []
    total_minutes = DAYS * 24 * 60
    n_points = total_minutes // FREQ_MIN

    timestamps = [START_DATE + timedelta(minutes=i * FREQ_MIN) for i in range(n_points)]

    for ts in timestamps:
        hour       = ts.hour + ts.minute / 60.0
        dow        = ts.weekday()
        is_weekend = dow >= 5

        # Base load
        consumption = profile["base_kwh"]

        # Morning peak
        consumption += gaussian_peak(hour, profile["peak_hour"],    width=1.5, height=profile["peak_kwh"])
        # Evening peak
        consumption += gaussian_peak(hour, profile["evening_hour"], width=1.2, height=profile["evening_kwh"] * 0.6)
        # Overnight dip (2–5 AM)
        night_dip   = 0.4 * np.exp(-0.5 * ((hour - 3.0) / 1.5) ** 2)
        consumption = max(consumption - night_dip, profile["base_kwh"] * 0.3)

        # Seasonal factor
        consumption *= seasonal_factor(ts.date(), profile["season_bias"])

        # Weekend factor
        if is_weekend:
            consumption *= profile["weekend_factor"]

        # Noise
        consumption += np.random.normal(0, profile["noise_std"])
        consumption  = max(consumption, 0.05)

        records.append({
            "timestamp":       ts.strftime("%Y-%m-%d %H:%M:%S"),
            "consumption_kwh": round(consumption, 4),
        })

    return pd.DataFrame(records)


def main():
    print("=" * 60)
    print(" Synthetic Energy Data Generator")
    print(f" Houses: {N_HOUSES} | Days: {DAYS} | Freq: {FREQ_MIN}min")
    print(" Columns: timestamp, consumption_kwh")
    print(" (features generated by data_preprocessing.py)")
    print("=" * 60)

    for house_id, profile in HOUSE_PROFILES.items():
        out_dir  = os.path.join("data", f"house_{house_id}")
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, "input_data.csv")

        print(f"\n[House {house_id:2d}] {profile['name']}")
        df = generate_house_data(house_id, profile)
        df.to_csv(out_path, index=False)

        print(f"  → {len(df):,} rows saved to {out_path}")
        print(f"  → consumption: min={df['consumption_kwh'].min():.3f}, "
              f"mean={df['consumption_kwh'].mean():.3f}, "
              f"max={df['consumption_kwh'].max():.3f} kWh")

    print("\n" + "=" * 60)
    print(" Done! Data ready for federated learning experiments.")
    print("=" * 60)


if __name__ == "__main__":
    main()