"""
Synthetic Energy Consumption Data Generator
============================================
Generates 90 days of energy consumption data for 10 houses with non-IID characteristics.

Output: data/house_{1..10}/input_data.csv
Format: timestamp, consumption_kwh
(All other features are generated by data_preprocessing.py)
"""

import os
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

# ── Reproducibility ─────────────────────────────────────────────
np.random.seed(42)

# ── Configuration ───────────────────────────────────────────────
N_HOUSES   = 10
DAYS       = 90
FREQ_MIN   = 10          # 10-minute intervals → 144 points/day
START_DATE = datetime(2024, 1, 1)

# ── House profiles (non-IID) ────────────────────────────────────
HOUSE_PROFILES = {
    # --- Original 5 houses (unchanged) ---
    1: {
        "name": "Small apartment, morning peak",
        "base_kwh":     0.3,
        "peak_hour":    7,
        "peak_kwh":     1.8,
        "evening_hour": 19,
        "evening_kwh":  1.2,
        "season_bias":  "winter",
        "noise_std":    0.08,
        "weekend_factor": 1.3,
    },
    2: {
        "name": "Large house, evening peak",
        "base_kwh":     0.7,
        "peak_hour":    20,
        "peak_kwh":     3.5,
        "evening_hour": 21,
        "evening_kwh":  3.0,
        "season_bias":  "summer",
        "noise_std":    0.15,
        "weekend_factor": 1.5,
    },
    3: {
        "name": "Medium house, work-from-home",
        "base_kwh":     0.5,
        "peak_hour":    12,
        "peak_kwh":     2.2,
        "evening_hour": 18,
        "evening_kwh":  1.8,
        "season_bias":  "neutral",
        "noise_std":    0.10,
        "weekend_factor": 1.1,
    },
    4: {
        "name": "Elderly couple, all-day moderate",
        "base_kwh":     0.6,
        "peak_hour":    11,
        "peak_kwh":     1.5,
        "evening_hour": 16,
        "evening_kwh":  1.4,
        "season_bias":  "winter",
        "noise_std":    0.07,
        "weekend_factor": 1.0,
    },
    5: {
        "name": "Young professionals, late night",
        "base_kwh":     0.25,
        "peak_hour":    22,
        "peak_kwh":     2.0,
        "evening_hour": 23,
        "evening_kwh":  1.8,
        "season_bias":  "summer",
        "noise_std":    0.12,
        "weekend_factor": 1.8,
    },
    # --- New 5 houses (distinct non-IID profiles) ---
    6: {
        "name": "Student flat, irregular schedule",
        "base_kwh":     0.2,
        "peak_hour":    14,
        "peak_kwh":     1.5,
        "evening_hour": 1,
        "evening_kwh":  1.3,
        "season_bias":  "neutral",
        "noise_std":    0.18,
        "weekend_factor": 2.0,
    },
    7: {
        "name": "Family with children, double morning peak",
        "base_kwh":     0.8,
        "peak_hour":    8,
        "peak_kwh":     4.0,
        "evening_hour": 18,
        "evening_kwh":  3.5,
        "season_bias":  "winter",
        "noise_std":    0.20,
        "weekend_factor": 1.6,
    },
    8: {
        "name": "Home office with EV charging",
        "base_kwh":     0.9,
        "peak_hour":    10,
        "peak_kwh":     5.0,
        "evening_hour": 20,
        "evening_kwh":  4.5,
        "season_bias":  "summer",
        "noise_std":    0.25,
        "weekend_factor": 1.2,
    },
    9: {
        "name": "Retired single, very low consumption",
        "base_kwh":     0.15,
        "peak_hour":    9,
        "peak_kwh":     0.8,
        "evening_hour": 15,
        "evening_kwh":  0.7,
        "season_bias":  "winter",
        "noise_std":    0.05,
        "weekend_factor": 1.05,
    },
    10: {
        "name": "Shift worker, inverted profile",
        "base_kwh":     0.3,
        "peak_hour":    6,
        "peak_kwh":     2.5,
        "evening_hour": 8,
        "evening_kwh":  2.0,
        "season_bias":  "neutral",
        "noise_std":    0.13,
        "weekend_factor": 0.8,  # less usage on weekends (works weekends, off weekdays)
    },
}

def seasonal_factor(date, bias):
    day_of_year = date.timetuple().tm_yday
    angle = 2 * np.pi * day_of_year / 365
    if bias == "winter":
        return 1.0 + 0.35 * np.cos(angle)
    elif bias == "summer":
        return 1.0 + 0.35 * (-np.cos(angle))
    else:
        return 1.0 + 0.10 * np.sin(angle)

def gaussian_peak(hour_float, center, width=1.5, height=1.0):
    return height * np.exp(-0.5 * ((hour_float - center) / width) ** 2)

def generate_house_data(house_id, profile):
    records = []
    total_minutes = DAYS * 24 * 60
    n_points = total_minutes // FREQ_MIN

    timestamps = [START_DATE + timedelta(minutes=i * FREQ_MIN) for i in range(n_points)]

    for ts in timestamps:
        hour       = ts.hour + ts.minute / 60.0
        dow        = ts.weekday()
        is_weekend = dow >= 5

        # Base load
        consumption = profile["base_kwh"]

        # Morning peak
        consumption += gaussian_peak(hour, profile["peak_hour"],    width=1.5, height=profile["peak_kwh"])
        # Evening peak
        consumption += gaussian_peak(hour, profile["evening_hour"], width=1.2, height=profile["evening_kwh"] * 0.6)
        # Overnight dip (2–5 AM)
        night_dip   = 0.4 * np.exp(-0.5 * ((hour - 3.0) / 1.5) ** 2)
        consumption = max(consumption - night_dip, profile["base_kwh"] * 0.3)

        # Seasonal factor
        consumption *= seasonal_factor(ts.date(), profile["season_bias"])

        # Weekend factor
        if is_weekend:
            consumption *= profile["weekend_factor"]

        # Noise
        consumption += np.random.normal(0, profile["noise_std"])
        consumption  = max(consumption, 0.05)

        records.append({
            "timestamp":       ts.strftime("%Y-%m-%d %H:%M:%S"),
            "consumption_kwh": round(consumption, 4),
        })

    return pd.DataFrame(records)


def main():
    print("=" * 60)
    print(" Synthetic Energy Data Generator")
    print(f" Houses: {N_HOUSES} | Days: {DAYS} | Freq: {FREQ_MIN}min")
    print(" Columns: timestamp, consumption_kwh")
    print(" (features generated by data_preprocessing.py)")
    print("=" * 60)

    for house_id, profile in HOUSE_PROFILES.items():
        out_dir  = os.path.join("data", f"house_{house_id}")
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, "input_data.csv")

        print(f"\n[House {house_id}] {profile['name']}")
        df = generate_house_data(house_id, profile)
        df.to_csv(out_path, index=False)

        print(f"  → {len(df):,} rows saved to {out_path}")
        print(f"  → consumption: min={df['consumption_kwh'].min():.3f}, "
              f"mean={df['consumption_kwh'].mean():.3f}, "
              f"max={df['consumption_kwh'].max():.3f} kWh")

    print("\n" + "=" * 60)
    print(" Done! Data ready for federated learning experiments.")
    print("=" * 60)


if __name__ == "__main__":
    main()