services:
  fog_app:
    image: fog_node_app:latest
    container_name: fog_main_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mqtt
    environment:
      - RABBITMQ_HOST=rabbitmq
      - FOG_HOST=rabbitmq
      - CLOUD_HOST=rabbitmq_cloud
      - FOG_RABBITMQ_HOST=rabbitmq
      - CLOUD_RABBITMQ_HOST=rabbitmq_cloud
      - FOG_MQTT_HOST=mqtt
      - FOG_MQTT_PORT=1883
      - CLOUD_MQTT_HOST=mqtt_cloud
      - CLOUD_MQTT_PORT=1883
      - HOST_IFACE=eth0
      - APP_HOST_PORT=8081
    ports:
      - "8084:8081"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - aqtf_shared_network
    command: uvicorn fog.communication.app_factory:app --host 0.0.0.0 --port 8081
    volumes:
      - ./models:/app/models
      - ./models/outbox:/app/models/outbox

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_fog
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - aqtf_shared_network

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt_fog
    ports:
      - "1883:1883"
    networks:
      - aqtf_shared_network

networks:
  aqtf_shared_network:
    external: true